### ISSUE TITLE
loss detail instruction for fixation

### ISSUE THREAD

**Issue by azuredsky** [MinglangQiao/MVVA-Database#2]
Does there a detail instruction for fixation, the shape like 001.npy is 600*2*34, as it notes 600 is frames, 2 coordinates is x,and y , so what does the 34 subjects mean?

**Comment by MinglangQiao** [comment]
Hello, there are 34 fixations for each video frame, capturing from 34 different subjects. Actually the sampling rate  of EyeLink 1000 plus  is larger than the fps of each video, thus we provide the fixations of each subject on all frames in our database.

**Comment by azuredsky** [comment]
Hi, how can I  get the talking face annotation?

**Comment by MinglangQiao** [comment]
@azuredsky Thanks for your interest, we will update the download link of talking face annotation  next week

**Comment by MinglangQiao** [comment]
@azuredsky Hi azuredsky, now the  talking face annotation can be download. Please refer to the README for more details.
